### PR TITLE
Should fix #48 dealing with the Aurelia 0.15.0 changes.

### LINKED ISSUE #48: Updates to support the Aurelia Framework v0.15.0
Per today's framework updates, there are changes to how plugins are handled.

```
Unhandled promise rejection TypeError: aurelia.globalizeResources is not a function
    at a.configure (http://localhost:9010/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.2/index.js:7:13)
    at http://localhost:9010/jspm_packages/github/aurelia/framework@0.15.0/aurelia-framework.js:34:34
```

`aurelia.globalizeResources` is now `aurelia.use.globalResources`

http://aurelia.io/docs.html#the-aurelia-object

There may be additional changes necessary that could be tacked onto this issue.

### PR DESCRIPTION
**Pull request by peisenmann**
This is to fix #48

### CODE REVIEW

**Comment by charlespockert** [comment]
Will merge this in as soon as the new git finishes updating (the Xbox One is eating 99.9% of my bandwidth! Damn these kids!)

**Comment by sn0rcha** [comment]
Hey There,

I just ran "jspm install github:charlespockert/aurelia-bs-grid" today and it's still got the same error. How do I install the fixed version?

Cheers,
Ben

**Comment by charlespockert** [comment]
@sn0rcha you'd have to install from master rather than the latest release which would be `jspm install github:charlespockert/aurelia-bs-grid@master` but bear in mind although I've merged the PR I've not actually tested it yet

**Comment by sn0rcha** [comment]
Many thanks for your reply!

I installed that ver but I get the following error:

```
ERROR [app-router] Error: Error instantiating Compiler. The argument at index 3 (key:undefined) could not be satisfied. Check the inner error for details.
------------------------------------------------
inner error: Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at Container.get (http://192.168.178.150:9000/jspm_packages/github/aurelia/dependency-injection@0.9.2/aurelia-dependency-injection.js:315:15)
```

My getSomeData function is:

```
    getSomeData(gridArgs) {
        return new Promise(function (resolve, reject) {
            resolve({
                data: [{id: 1, name: 'Ping'}, {id: 2, name: 'Ben'}],
                count: 2
            });
        });
    }
```

Just a heads up in case you're fixing something, unless you can see something I've done wrong :)

**Pull request merged**
